---

- name: configure ngx yum repo
  template:
    src: bf-ngx.repo.j2
    dest: /etc/yum.repos.d/bf-ngx.repo
  become: yes
  notify: clean yum cache

- name: copy nginx index.html
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
